name: store_mood_app
description: "SpazioCosmeticApp."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  http: ^1.6.0
  image_picker: ^1.1.2
  mime: ^1.0.6
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Librería para generar los íconos de la app
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/img/Logo.png

# Configuración automática para inyectar tu logo en Android e iOS
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/img/Logo.png"